# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/tsl.jpg', max_length=200, null=True, upload_to='avatar/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
